"""add pdf fields

Revision ID: 98f2c4a6ac24
Revises: 4b1dcbe424b9
Create Date: 2026-06-09 16:46:52.469922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f2c4a6ac24'
down_revision: Union[str, Sequence[str], None] = '4b1dcbe424b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('pdf_url', sa.String(), nullable=True))
    op.add_column('information', sa.Column('pdf_storage_path', sa.String(), nullable=True))
    op.alter_column('information', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('information', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('information', 'pdf_storage_path')
    op.drop_column('information', 'pdf_url')
    # ### end Alembic commands ###
